name: Autograding Tests
on:
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]' && github.actor != 'jacobsteffenBYU'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12.6
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install pytest pytest-subtests 'black<=22.3.0' 'tomli>=1.1.0' 'timeout-decorator~=0.5.0'
    - name: tests/test_01_input_prompts.py
      id: tests-test-01-input-prompts-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-01-input-prompts
        setup-command: ''
        command: python -m pytest -v tests/test_01_input_prompts.py
        timeout: 30
        max-score: 10
    - name: tests/test_02_printed_messages.py
      id: tests-test-02-printed-messages-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-02-printed-messages
        setup-command: ''
        command: python -m pytest -v tests/test_02_printed_messages.py
        timeout: 30
        max-score: 10
    - name: tests/test_03_soccer_team_class.py
      id: tests-test-03-soccer-team-class-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-03-soccer-team-class
        setup-command: ''
        command: python -m pytest -v tests/test_03_soccer_team_class.py
        timeout: 30
        max-score: 10
    - name: tests/test_04_sponsored_team_class.py
      id: tests-test-04-sponsored-team-class-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-04-sponsored-team-class
        setup-command: ''
        command: python -m pytest -v tests/test_04_sponsored_team_class.py
        timeout: 30
        max-score: 10
    - name: tests/test_05_game_class.py
      id: tests-test-05-game-class-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-05-game-class
        setup-command: ''
        command: python -m pytest -v tests/test_05_game_class.py
        timeout: 30
        max-score: 10
    - name: tests/test_06_soccer_team_record_win.py
      id: tests-test-06-soccer-team-record-win-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-06-soccer-team-record-win
        setup-command: ''
        command: python -m pytest -v tests/test_06_soccer_team_record_win.py
        timeout: 30
        max-score: 3
    - name: tests/test_07_soccer_team_record_loss.py
      id: tests-test-07-soccer-team-record-loss-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-07-soccer-team-record-loss
        setup-command: ''
        command: python -m pytest -v tests/test_07_soccer_team_record_loss.py
        timeout: 30
        max-score: 3
    - name: tests/test_08_soccer_team_get_record_percentage.py
      id: tests-test-08-soccer-team-get-record-percentage-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-08-soccer-team-get-record-percentage
        setup-command: ''
        command: python -m pytest -v tests/test_08_soccer_team_get_record_percentage.py
        timeout: 30
        max-score: 5
    - name: tests/test_09_soccer_team_generate_score.py
      id: tests-test-09-soccer-team-generate-score-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-09-soccer-team-generate-score
        setup-command: ''
        command: python -m pytest -v tests/test_09_soccer_team_generate_score.py
        timeout: 30
        max-score: 5
    - name: tests/test_10_soccer_team_get_season_message.py
      id: tests-test-10-soccer-team-get-season-message-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-10-soccer-team-get-season-message
        setup-command: ''
        command: python -m pytest -v tests/test_10_soccer_team_get_season_message.py
        timeout: 30
        max-score: 5
    - name: tests/test_11_sponsored_team_generate_score.py
      id: tests-test-11-sponsored-team-generate-score-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-11-sponsored-team-generate-score
        setup-command: ''
        command: python -m pytest -v tests/test_11_sponsored_team_generate_score.py
        timeout: 30
        max-score: 5
    - name: tests/test_12_sponsored_team_get_season_message.py
      id: tests-test-12-sponsored-team-get-season-message-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-12-sponsored-team-get-season-message
        setup-command: ''
        command: python -m pytest -v tests/test_12_sponsored_team_get_season_message.py
        timeout: 30
        max-score: 5
    - name: tests/test_13_game_play_game.py
      id: tests-test-13-game-play-game-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-13-game-play-game
        setup-command: ''
        command: python -m pytest -v tests/test_13_game_play_game.py
        timeout: 30
        max-score: 13
    - name: tests/test_14_no_tie_scores.py
      id: tests-test-14-no-tie-scores-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-14-no-tie-scores
        setup-command: ''
        command: python -m pytest -v tests/test_14_no_tie_scores.py
        timeout: 30
        max-score: 5
    - name: tests/test_15_sufficient_comments.py
      id: tests-test-15-sufficient-comments-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-15-sufficient-comments
        setup-command: ''
        command: python -m pytest -v tests/test_15_sufficient_comments.py
        timeout: 30
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS-TEST-01-INPUT-PROMPTS-PY_RESULTS: ${{steps.tests-test-01-input-prompts-py.outputs.result}}
        TESTS-TEST-02-PRINTED-MESSAGES-PY_RESULTS: ${{steps.tests-test-02-printed-messages-py.outputs.result}}
        TESTS-TEST-03-SOCCER-TEAM-CLASS-PY_RESULTS: ${{steps.tests-test-03-soccer-team-class-py.outputs.result}}
        TESTS-TEST-04-SPONSORED-TEAM-CLASS-PY_RESULTS: ${{steps.tests-test-04-sponsored-team-class-py.outputs.result}}
        TESTS-TEST-05-GAME-CLASS-PY_RESULTS: ${{steps.tests-test-05-game-class-py.outputs.result}}
        TESTS-TEST-06-SOCCER-TEAM-RECORD-WIN-PY_RESULTS: ${{steps.tests-test-06-soccer-team-record-win-py.outputs.result}}
        TESTS-TEST-07-SOCCER-TEAM-RECORD-LOSS-PY_RESULTS: ${{steps.tests-test-07-soccer-team-record-loss-py.outputs.result}}
        TESTS-TEST-08-SOCCER-TEAM-GET-RECORD-PERCENTAGE-PY_RESULTS: ${{steps.tests-test-08-soccer-team-get-record-percentage-py.outputs.result}}
        TESTS-TEST-09-SOCCER-TEAM-GENERATE-SCORE-PY_RESULTS: ${{steps.tests-test-09-soccer-team-generate-score-py.outputs.result}}
        TESTS-TEST-10-SOCCER-TEAM-GET-SEASON-MESSAGE-PY_RESULTS: ${{steps.tests-test-10-soccer-team-get-season-message-py.outputs.result}}
        TESTS-TEST-11-SPONSORED-TEAM-GENERATE-SCORE-PY_RESULTS: ${{steps.tests-test-11-sponsored-team-generate-score-py.outputs.result}}
        TESTS-TEST-12-SPONSORED-TEAM-GET-SEASON-MESSAGE-PY_RESULTS: ${{steps.tests-test-12-sponsored-team-get-season-message-py.outputs.result}}
        TESTS-TEST-13-GAME-PLAY-GAME-PY_RESULTS: ${{steps.tests-test-13-game-play-game-py.outputs.result}}
        TESTS-TEST-14-NO-TIE-SCORES-PY_RESULTS: ${{steps.tests-test-14-no-tie-scores-py.outputs.result}}
        TESTS-TEST-15-SUFFICIENT-COMMENTS-PY_RESULTS: ${{steps.tests-test-15-sufficient-comments-py.outputs.result}}
      with:
        runners: tests-test-01-input-prompts-py,tests-test-02-printed-messages-py,tests-test-03-soccer-team-class-py,tests-test-04-sponsored-team-class-py,tests-test-05-game-class-py,tests-test-06-soccer-team-record-win-py,tests-test-07-soccer-team-record-loss-py,tests-test-08-soccer-team-get-record-percentage-py,tests-test-09-soccer-team-generate-score-py,tests-test-10-soccer-team-get-season-message-py,tests-test-11-sponsored-team-generate-score-py,tests-test-12-sponsored-team-get-season-message-py,tests-test-13-game-play-game-py,tests-test-14-no-tie-scores-py,tests-test-15-sufficient-comments-py
